set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

find_program(S3G_MINGW_C_COMPILER
  NAMES x86_64-w64-mingw32-gcc
  REQUIRED)
find_program(S3G_MINGW_CXX_COMPILER
  NAMES x86_64-w64-mingw32-g++
  REQUIRED)
find_program(S3G_MINGW_RC_COMPILER
  NAMES x86_64-w64-mingw32-windres
  REQUIRED)

set(CMAKE_C_COMPILER "${S3G_MINGW_C_COMPILER}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${S3G_MINGW_CXX_COMPILER}" CACHE FILEPATH "" FORCE)
set(CMAKE_RC_COMPILER "${S3G_MINGW_RC_COMPILER}" CACHE FILEPATH "" FORCE)

execute_process(
  COMMAND "${S3G_MINGW_C_COMPILER}" -print-sysroot
  OUTPUT_VARIABLE S3G_MINGW_SYSROOT
  OUTPUT_STRIP_TRAILING_WHITESPACE
  COMMAND_ERROR_IS_FATAL ANY)

set(CMAKE_FIND_ROOT_PATH "${S3G_MINGW_SYSROOT}" CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# Max's import libraries live in max-sdk-base rather than in the MinGW
# sysroot, so target library and header searches must consider both.
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
# Do not let macOS host frameworks win while targeting Windows.
set(CMAKE_FIND_FRAMEWORK NEVER)
